### ISSUE TITLE
Enable greenkeeper

### ISSUE THREAD

**Issue by cemremengu** [fastify/fastify-routes#1]
@mcollina could you please try to see if it can be enabled now?

**Comment by cemremengu** [comment]
GK Looks good and travis pretty please 😄

**Comment by cemremengu** [comment]
Travis still not triggered

**Comment by mcollina** [comment]
https://travis-ci.com/fastify/fastify-routes < seems to be.

**Comment by cemremengu** [comment]
There is also this which looks like the correct one and fails (.org site where badge points to)

https://travis-ci.org/fastify/fastify-routes

**Comment by mcollina** [comment]
you'll need to change the badge.

Il giorno mar 2 ott 2018 alle ore 21:45 Cemre Mengu <
notifications@github.com> ha scritto:

**Comment by cemremengu** [comment]
Ok it's fixed now. I enabled it under the fastify organization. I contacted them to delete the other one under my name since they transferred it to a pro account with only 100 builds.

Thanks for your help and apologies for spamming you with this
