### ISSUE TITLE
v6.0.0 is a pre-release which is unexpected when trying to upgrade to Fastify v5

### ISSUE THREAD

**Issue by hershmire** [fastify/fastify-routes#109]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

5.x.x

### Plugin version

6.0.0

### Node.js version

20.x

### Operating system

macOS

### Operating system version (i.e. 20.04, 11.3, 10)

15.0.1

### Description

v6.0.0 was released as a prerelease which seems accidental.

### Expected Behavior

v6.0.0 to be latest release that supports Fastify v5.

**Comment by mcollina** [comment]
Fixed
