### ISSUE TITLE
Add Typescript definitions

### ISSUE THREAD

**Issue by mnlfischer** [fastify/fastify-routes#35]
## 🚀 Feature Proposal

Add missing Typescript definitions.

## Motivation

I would like to use fastify-routes in a Typescript project, especially for testing registered routes. I did not found any type definitions in this project or some definitions from [https://www.npmjs.com/~types](https://www.npmjs.com/~types).

Would be happy if you can support Typescript in the future. I'm not so deep into TS definitions but with some practice I can support.

## Example

No example needed.

**Comment by mcollina** [comment]
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

Use fastify-static as a starting point.

**Comment by mnlfischer** [comment]
I'm on vacation for the next two weeks. I look at it after.

**Comment by Fdawgs** [comment]
@mnlfischer has #44 resolved this?
