### ISSUE TITLE
The map provided by .routes is empty

### ISSUE THREAD

**Issue by punowo** [fastify/fastify-routes#90]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

4.17.0

### Plugin version

5.1.0

### Node.js version

18.16.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

11

### Description

I'm looking for a way to get information about fastify routes so that I can parse and output some of that to a file. I've setup a barebones npm project so I can play around with plugins. 

### Steps to Reproduce

```
const fastify = require("fastify")({
  logger: true,
});
fastify.register(require("@fastify/routes"));

fastify.get("/hello", async (request, reply) => {
  return { hello: "world" };
});

fastify.listen({ port: 3000 }, function (err, address) {
  if (err) {
    fastify.log.error(err);
    process.exit(1);
  }
  console.log(fastify.routes);
});

```

### Expected Behavior

I would expect the Map to not be empty.
``` 
{"level":30,"time":1685619932741,"pid":19812,"hostname":"vasilache","msg":"Server listening at http://[::1]:3000"}
{"level":30,"time":1685619932743,"pid":19812,"hostname":"vasilache","msg":"Server listening at http://127.0.0.1:3000"}
Map(0) {}
```

**Comment by Uzlopak** [comment]
I think .register() should be awaited.

**Comment by derammo** [comment]
I just came here to report that the example code in the README.md does not work because it requires await() or then().   This issue should probably be reopened to fix the /README.md?

**Comment by derammo** [comment]
see PR in #95
